import { citiesModel } from "../models/cities.model";

export const cities: citiesModel[] = [
  { city: "Bogotá", department: "Cundinamarca" },
  { city: "Medellín", department: "Antioquia" },
  { city: "Cali", department: "Valle del Cauca" },
  { city: "Barranquilla", department: "Atlántico" },
  { city: "Cartagena", department: "Bolívar" },
  { city: "Cúcuta", department: "Norte de Santander" },
  { city: "Bucaramanga", department: "Santander" },
  { city: "Pereira", department: "Risaralda" },
  { city: "Santa Marta", department: "Magdalena" },
  { city: "Ibagué", department: "Tolima" },
  { city: "Pasto", department: "Nariño" },
  { city: "Manizales", department: "Caldas" },
  { city: "Neiva", department: "Huila" },
  { city: "Villavicencio", department: "Meta" },
  { city: "Armenia", department: "Quindío" },
  { city: "Popayán", department: "Cauca" },
  { city: "Valledupar", department: "Cesar" },
  { city: "Montería", department: "Córdoba" },
  { city: "Sincelejo", department: "Sucre" },
  { city: "Tunja", department: "Boyacá" },
  { city: "Riohacha", department: "La Guajira" },
  { city: "Quibdó", department: "Chocó" },
  { city: "Florencia", department: "Caquetá" },
  { city: "Yopal", department: "Casanare" },
  { city: "Mocoa", department: "Putumayo" },
  { city: "Arauca", department: "Arauca" },
  { city: "San José del Guaviare", department: "Guaviare" },
  { city: "Mitú", department: "Vaupés" },
  { city: "Puerto Carreño", department: "Vichada" },
  { city: "Inírida", department: "Guainía" },
  { city: "Leticia", department: "Amazonas" },
  { city: "San Andrés", department: "San Andrés y Providencia" },
];
